version: '3.9'

services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  
  skavtko-clani:
    image: skavtko-clani:alpine-1
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_DRIVER=${DB_DRIVER}
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 8071:8071
  skavtko-skupine:
    image: skavtko-skupine:alpine-1
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_DRIVER=${DB_DRIVER}
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 8072:8062
  skavtko-srecanja:
    image: skavtko-srecanja:alpine-1
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_DRIVER=${DB_DRIVER}
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 8073:8073
  skavtko-prisotnosti:
    image: skavtko-prisotnosti:alpine-1
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_DRIVER=${DB_DRIVER}
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 8074:8074
  skavtko-osebnospremljanje:
    image: skavtko-osebnospremljanje:alpine-1
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_DRIVER=${DB_DRIVER}
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 8075:8075
  skavtko-termini:
    image: skavtko-termini:alpine-1
    restart: always
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PSW=${DB_PSW}
      - DB_DRIVER=${DB_DRIVER}
      - KAFKA_URL=${KAFKA_URL}
    ports:
      - 8076:8076