version: '3.9'

services:
  skavtko-api:
    image: skavtko:alpine-1
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5435/db
      - DB_USER=admin
      - DB_PSW=admin
      - DB_DRIVER=org.postgresql.Driver
    ports:
      - 8082:8080