apiVersion: v1
kind: Service
metadata:
  name: skavtko-api-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-name: "skavtko-api"
spec:
  selector:
    app: skavtko
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer