apiVersion: v1
kind: Service
metadata:
  name: skavtko-api-service
spec:
  selector:
    app: skavtko
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer