apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skavtko-os-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skavtko-os
  minReplicas: 1       # Minimum number of replicas
  maxReplicas: 5      # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization percentage
