kumuluzee:
  datasources:
    - jndi-name: jdbc/SkavtkoDS
      connection-url: jdbc:postgresql://localhost:5435/db
      username: admin
      password: admin
      pool:
        max-size: 2
  persistence-units:
    - name: "skavtko"
      continue-on-error: false